// <auto-generated />
using System;
using MVD_CRL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVD_CRL.Migrations
{
    [DbContext(typeof(MVD_CarlContext))]
    [Migration("20210521134547_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVD_CRL.Models.ВидыПреступлений", b =>
                {
                    b.Property<int>("КодВидаПреступления")
                        .HasColumnName("Код_вида_преступления")
                        .HasColumnType("int");

                    b.Property<string>("Наименование")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Наказание")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Срок")
                        .HasColumnType("int");

                    b.Property<string>("Статья")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("КодВидаПреступления")
                        .HasName("PK__Виды_пре__C2E8B24414EB3E63");

                    b.ToTable("Виды_преступлений");
                });

            modelBuilder.Entity("MVD_CRL.Models.Должности", b =>
                {
                    b.Property<int>("КодДолжности")
                        .HasColumnName("Код_должности")
                        .HasColumnType("int");

                    b.Property<string>("НаименованиеДолжности")
                        .HasColumnName("Наименование_должности")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Обязанности")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Оклад")
                        .HasColumnType("int");

                    b.Property<string>("Требования")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("КодДолжности")
                        .HasName("PK__Должност__6F49B82E1D6C000B");

                    b.ToTable("Должности");
                });

            modelBuilder.Entity("MVD_CRL.Models.Звания", b =>
                {
                    b.Property<int>("КодЗвания")
                        .HasColumnName("Код_звания")
                        .HasColumnType("int");

                    b.Property<int?>("Надбавка")
                        .HasColumnType("int");

                    b.Property<string>("Наименование")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Обязанности")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Требования")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("КодЗвания")
                        .HasName("PK__Звания__590635FC51286356");

                    b.ToTable("Звания");
                });

            modelBuilder.Entity("MVD_CRL.Models.Пострадавшие", b =>
                {
                    b.Property<int>("КодПострадавшего")
                        .HasColumnName("Код_пострадавшего")
                        .HasColumnType("int");

                    b.Property<string>("Адрес")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ДатаРождения")
                        .HasColumnName("Дата_рождения")
                        .HasColumnType("date");

                    b.Property<string>("Пол")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Фио")
                        .HasColumnName("ФИО")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("КодПострадавшего")
                        .HasName("PK__Пострада__797BA8E29F4973AF");

                    b.ToTable("Пострадавшие");
                });

            modelBuilder.Entity("MVD_CRL.Models.Преступники", b =>
                {
                    b.Property<int>("НомерДела")
                        .HasColumnName("Номер_дела")
                        .HasColumnType("int");

                    b.Property<string>("Адрес")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ДатаРождения")
                        .HasColumnName("Дата_рождения")
                        .HasColumnType("date");

                    b.Property<int>("КодВидаПреступления")
                        .HasColumnName("Код_вида_преступления")
                        .HasColumnType("int");

                    b.Property<int>("КодПострадавшего")
                        .HasColumnName("Код_пострадавшего")
                        .HasColumnType("int");

                    b.Property<int>("КодСотрудника")
                        .HasColumnName("Код_сотрудника")
                        .HasColumnType("int");

                    b.Property<string>("Пол")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Состояние")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Фио")
                        .HasColumnName("ФИО")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("НомерДела")
                        .HasName("PK__Преступн__A3C5D89E181AAD63");

                    b.HasIndex("КодВидаПреступления");

                    b.HasIndex("КодПострадавшего");

                    b.HasIndex("КодСотрудника");

                    b.ToTable("Преступники");
                });

            modelBuilder.Entity("MVD_CRL.Models.Сотрудники", b =>
                {
                    b.Property<int>("КодСотрудника")
                        .HasColumnName("Код_сотрудника")
                        .HasColumnType("int");

                    b.Property<string>("Адрес")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Возраст")
                        .HasColumnType("int");

                    b.Property<int>("КодДолжности")
                        .HasColumnName("Код_должности")
                        .HasColumnType("int");

                    b.Property<int>("КодЗвания")
                        .HasColumnName("Код_звания")
                        .HasColumnType("int");

                    b.Property<string>("ПаспортныеДанные")
                        .HasColumnName("Паспортные_данные")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Пол")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Телефон")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Фио")
                        .HasColumnName("ФИО")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("КодСотрудника")
                        .HasName("PK__Сотрудни__409003AE3329DB43");

                    b.HasIndex("КодДолжности");

                    b.HasIndex("КодЗвания");

                    b.ToTable("Сотрудники");
                });

            modelBuilder.Entity("MVD_CRL.Models.Преступники", b =>
                {
                    b.HasOne("MVD_CRL.Models.ВидыПреступлений", "КодВидаПреступленияNavigation")
                        .WithMany("Преступники")
                        .HasForeignKey("КодВидаПреступления")
                        .HasConstraintName("FK__Преступни__Код_в__1DE57479")
                        .IsRequired();

                    b.HasOne("MVD_CRL.Models.Пострадавшие", "КодПострадавшегоNavigation")
                        .WithMany("Преступники")
                        .HasForeignKey("КодПострадавшего")
                        .HasConstraintName("FK__Преступни__Код_п__1CF15040")
                        .IsRequired();

                    b.HasOne("MVD_CRL.Models.Сотрудники", "КодСотрудникаNavigation")
                        .WithMany("Преступники")
                        .HasForeignKey("КодСотрудника")
                        .HasConstraintName("FK__Преступни__Код_с__1BFD2C07")
                        .IsRequired();
                });

            modelBuilder.Entity("MVD_CRL.Models.Сотрудники", b =>
                {
                    b.HasOne("MVD_CRL.Models.Должности", "КодДолжностиNavigation")
                        .WithMany("Сотрудники")
                        .HasForeignKey("КодДолжности")
                        .HasConstraintName("FK__Сотрудник__Код_д__182C9B23")
                        .IsRequired();

                    b.HasOne("MVD_CRL.Models.Звания", "КодЗванияNavigation")
                        .WithMany("Сотрудники")
                        .HasForeignKey("КодЗвания")
                        .HasConstraintName("FK__Сотрудник__Код_з__1920BF5C")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
